class QuizData {
  static Map<String, String> ebiQuizData = {
    'コイ': 'carp',
    'ナマズ': 'catfish',
    'タラ': 'cod',
    'イルカ': 'dolphin',
    'ウナギ': 'eel',
    'ニシン': 'herring',
    'クラゲ': 'jellyfish',
    'サバ': 'mackerel',
    'タコ': 'octopus',
    'サケ': 'salmon',
    'アシカ': 'seal',
    'サメ': 'shark',
    'イカ': 'squid',
    'アカエイ': 'stingray',
    'サケ、マス、イワナ、トラウト': 'trout',
    'マグロ': 'tuna',
    'セイウチ': 'walrus',
    'クジラ': 'whale',
    'エイ': 'ray',
    '甲殻類': 'crustacean',
    'カニ': 'crab',
    'ザリガニ': 'crayfish',
    'ロブスター': 'lobster',
    'カキ': 'oyster',
    'クルマエビ、テナガエビ': 'prawn',
    'エビ': 'shrimp',
    'ヒトデ': 'starfish',
    'ヒレ': 'fin',
    'エラ': 'gills',
    'ウロコ': 'scales',
    'エビなどのはさみ': 'pincers'
  };
}
