class QuizData {
  static Map<String, String> ebiQuizData = {
    'コイ': 'carp',
    'ナマズ': 'catfish',
    'タラ': 'cod',
    'イルカ': 'dolphin',
    'ウナギ': 'eel',
    'ニシン': 'herring',
    'クラゲ': 'jellyfish',
    'サバ': 'mackerel',
    'タコ': 'octopus',
    'サケ': 'salmon',
    'アシカ': 'seal',
    'サメ': 'shark',
    'イカ': 'squid',
    'アカエイ': 'stingray',
    'サケ、マス、イワナ、トラウト': 'trout',
    'マグロ': 'tuna',
    'セイウチ': 'walrus',
    'クジラ': 'whale',
    'エイ': 'ray',
    '甲殻類': 'crustacean',
    'カニ': 'crab',
    'ザリガニ': 'crayfish',
    'ロブスター': 'lobster',
    'カキ、オイスター': 'oyster',
    'クルマエビ、テナガエビ、エビ': 'prawn',
    'エビ': 'shrimp',
    'ヒトデ': 'starfish',
    'ヒレ': 'fin',
    'エラ': 'gills',
    'ウロコ': 'scales',
    'エビやロブスターなどのはさみ': 'pincers'
  };
  static Map<String, String> l1QuizData = {
    'リンゴ': 'apple',
    'バナナ': 'banana',
    'サクラ': 'cherry',
    'ブドウ': 'grape',
    'オレンジ': 'orange',
    'モモ': 'peach',
    'ナシ': 'pear',
    'パイナップル': 'pineapple',
    'スイカ': 'watermelon',
    'ニンジン': 'carrot',
    'トマト': 'tomato',
    'ジャガイモ': 'potato',
    'キャベツ': 'cabbage',
    'ブロッコリー': 'broccoli',
    'キュウリ': 'cucumber',
    'トウモロコシ': 'corn',
    'ピーマン': 'green pepper',
    'ナス': 'eggplant',
    'タマネギ': 'onion',
    'ホウレンソウ': 'spinach',
    'コショウ': 'pepper',
    'ショウガ': 'ginger',
    'サトイモ': 'taro',
    'イチゴ': 'strawberry',
    'アボカド': 'avocado',
    'クルミ': 'walnut',
    'アーモンド': 'almond',
    'クッキー': 'cookie',
    'ケーキ': 'cake',
    'アイスクリーム': 'ice cream',
    'スープ': 'soup',
    'パン': 'bread',
    'バター': 'butter',
    'チーズ': 'cheese',
    'ヨーグルト': 'yogurt',
    'サラダ': 'salad',
    'スパゲティ': 'spaghetti',
    'ソース': 'sauce',
    'チョコレート': 'chocolate',
    'キャンディ': 'candy',
    'おにぎり': 'rice ball',
    'すし': 'sushi',
    'てんぷら': 'tempura',
    'みそしる': 'miso soup',
    'さしみ': 'sashimi',
    'とうふ': 'tofu',
    'もち': 'rice cake',
    'わさび': 'wasabi',
    'おちゃ': 'green tea',
    'こうちゃ': 'black tea',
    'コーヒー': 'coffee',
    'ジュース': 'juice',
    'みず': 'water',
    'ミルク': 'milk',
    'サケ': 'sake',
  };
}
