class QuizData {
  static Map<String, String> ebiQuizData = {
    'コイ': 'carp',
    'ナマズ': 'catfish',
    'タラ': 'cod',
    'ウナギ': 'eel',
    'ニシン': 'herring',
    'クラゲ': 'jellyfish',
    'サバ': 'mackerel',
    'アシカ': 'seal',
    'アカエイ': 'stingray',
    'イワナ': 'trout',
    'セイウチ': 'walrus',
    'クジラ': 'whale',
    'エイ': 'ray',
    '甲殻類': 'crustacean',
    'ザリガニ': 'crayfish',
    'ロブスター': 'lobster',
    'クルマエビ': 'prawn',
    'エラ': 'gills',
    'ウロコ': 'scales',
    'エビのはさみ': 'pincers',
    'アザラシ': 'seal',
    'ホタテ': 'scallop',
    'アワビ': 'abalone',
    'ウミガメ': 'sea turtle',
    'ウニ': 'sea urchin',
    'ナマコ': 'sea cucumber',
    'サンゴ': 'coral',
    'クモヒトデ': 'brittle star',
    'タラバガニ': 'king crab',
    'ハマグリ': 'clam',
    'アオリイカ': 'cuttlefish',
    'シャコ': 'mantis shrimp',
    'ホウボウ': 'gurnard',
    'ギンザメ': 'chimaera',
    'オキアミ': 'krill',
    'ヤドカリ': 'hermit crab',
    'ウミウシ': 'nudibranch',
    'カブトガニ': 'horseshoe crab',
    'ラッコ': 'sea otter',
    'トビウオ': 'flying fish',
    'ダンゴウオ': 'lumpsucker',
    'ハナイカ': 'flamboyant cuttlefish',
    'フサカサゴ': 'lionfish',
    'クモガニ': 'spider crab',
    'ウミサソリ': 'sea scorpion',
    'カイアシ': 'copepod',
    'オワンクラゲ': 'moon jellyfish',
    'ミズクラゲ': 'aurelia jellyfish',
    'ウミクモ': 'sea spider',
    'ウミタナゴ': 'surfperch',
    'タルマワシ': 'pelagic amphipod',
    'ホウネンエビ': 'fairy shrimp',
    'ヨコエビ': 'sand hopper',
    'ムールガイ': 'mussel',
    'イシガキダイ': 'spotted knifejaw',
    'ミノカサゴ': 'scorpionfish',
    'コペポーダ': 'copepod (scientific term)',
    'テッポウエビ': 'pistol shrimp',
    'ミズムシ': 'water louse',
  };
  static Map<String, String> l1QuizData = {
    'リンゴ': 'apple',
    'バナナ': 'banana',
    'サクラ': 'cherry',
    'ブドウ': 'grape',
    'オレンジ': 'orange',
    'モモ': 'peach',
    'ナシ': 'pear',
    'パイナップル': 'pineapple',
    'スイカ': 'watermelon',
    'ニンジン': 'carrot',
    'トマト': 'tomato',
    'ジャガイモ': 'potato',
    'キャベツ': 'cabbage',
    'ブロッコリー': 'broccoli',
    'キュウリ': 'cucumber',
    'トウモロコシ': 'corn',
    'ピーマン': 'green pepper',
    'ナス': 'eggplant',
    'タマネギ': 'onion',
    'ホウレンソウ': 'spinach',
    'コショウ': 'pepper',
    'ショウガ': 'ginger',
    'サトイモ': 'taro',
    'イチゴ': 'strawberry',
    'アボカド': 'avocado',
    'クルミ': 'walnut',
    'アーモンド': 'almond',
    'クッキー': 'cookie',
    'ケーキ': 'cake',
    'アイスクリーム': 'ice cream',
    'スープ': 'soup',
    'パン': 'bread',
    'バター': 'butter',
    'チーズ': 'cheese',
    'ヨーグルト': 'yogurt',
    'サラダ': 'salad',
    'スパゲティ': 'spaghetti',
    'ソース': 'sauce',
    'チョコレート': 'chocolate',
    'キャンディ': 'candy',
    'おにぎり': 'rice ball',
    'すし': 'sushi',
    'てんぷら': 'tempura',
    'みそしる': 'miso soup',
    'さしみ': 'sashimi',
    'とうふ': 'tofu',
    'もち': 'rice cake',
    'わさび': 'wasabi',
    'おちゃ': 'green tea',
    'こうちゃ': 'black tea',
    'コーヒー': 'coffee',
    'ジュース': 'juice',
    'みず': 'water',
    'ミルク': 'milk',
    'サケ': 'sake',
  };
}
